### ISSUE TITLE
Dealing Cards

### ISSUE THREAD

**Issue by ZombieRoxtar** [ZombieRoxtar/SDLitaire#1]
Before I give cards faces/values I need to their deal behavior to be predictable. There's an almost accidental error correction where cards that are "dropped" outside a valid place are recalled (to the main deck in this case). I need help determining what I did to their flight paths.

**Comment by aroxby** [comment]
I left you some feedback that you can look into.  Also, I hate to say this but have you considered making this game in Unity?  I really hate to throw away all your hard work but it would be faster.  Also bonus: Unity has a nice engine already setup, so it will guide you towards more standard game dev techniques.

**Comment by ZombieRoxtar** [comment]
This seems to have been fixed when I fixed what I thought was the as-of-yet unneeded capability to make a card fly up or left.
